services:
  # chromadb:
  #   image: chromadb/chroma
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./data_pipeline/data/drugs_files/db:/data

  gateway:
    image: hsh24/gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - medicine-detection-service
      - ocr-service
      - drug-extractor-service
      - drug-interaction-service
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "5000"
      DETECTION_URL: "http://medicine-detection-service:5001/detect"
      OCR_URL: "http://ocr-service:5001/extracted_text"
      EXTRACTOR_URL: "http://drug-extractor-service:5000/extract"
      INTERACTION_URL: "http://drug-interaction-service:8000/rag"
    networks:
      - app-network

  medicine-detection-service:
    image: hsh24/medicine-detection-model:latest
    container_name: medicine-detection-service
    ports:
      - "5001:5001"
    networks:
      - app-network

  ocr-service:
    image: safaasalman/ocr-service:latest
    container_name: ocr-service
    ports:
      - "5002:5001"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/key.json"
      APP_HOST: "0.0.0.0"
      APP_PORT: "5001"
      TYPE: "service_account"
      PROJECT_ID: "ai-industry-projecr"
      PRIVATE_KEY_ID: "a704038c00a082cb5da72be187de0aa660b21701"
      PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCimdMfTju07MAx\nmb5ktRLXgKa2bIz6j6L28LZKsyOp/f4/H9yyPiXbWXf16UggauHXJYS8Uc0Aaxxo\nud40YFLdL2lcxZRBJR7yzv3MfW4LDRujI1zHR1JSxubARPUg+IBP/8dMoeVV15Hx\nRFHI6tVqSUQfsDg0SlBjYZSipdCZlLzN5r1vwnBbaQzZwwcyMzBsK2cmZrDrRE7D\nsBs/lgeJ2lWwzteS4ktlY8+8uiF3EeY2fLmy2hLed/PXGcaYig/VAwUgq8UXkgRE\nPvaNCjTuZoCsqNqQVxwj/Nwvkdsbm1OVbZd02JPceqDX0XC3laUtV0sWt0T4WTqT\nCB7E8WtTAgMBAAECggEAEA01bU1mJtnfA0Z/0tCZTT2TDPExsvkuXPMDBo7MAi0O\ncKGEQkhQ/mgaUo62oxSfZNjRqLGT65WnVqNP+fBZsyIfZEbQ+DliO8AOsqWIkSi4\ncLtonkzpJejNa2+jRJ+jiGzh+iuv8xshJNCEw7EtuPIF+pwv1YxR2+23JEili3Od\n+8R9uFvok3xU2Th4lBIn9UsxrAI8O3d7sdN9WymeHesE0We2doq6WV9FJcDH69tk\nD5wHntgYPgt0uUZAlLaVjL8ZLe9wEOCE8MqJXRFsM+tfg38qhA06/Xd8blUH0kCD\ntrhqxLwBvJyssA2E9fwzBUnq9KrPXJUsGBeKuLeHuQKBgQDhPngvroBnVGe2cTCK\n+a9lvCVX2qau6PH4GP/2jBUtaA4NWgBxRdOxNe4foG42XNeC4aDQba3EH8JSNsyu\nnOnklC+QUA5xALWB7xS3NhzYQl1cu2fItAhFJkBPa1qNCnuvoy35N2r3n2leTjX+\nAhWziqta6hSiA5zNRjWLUjcP/wKBgQC4zaEQfAojv1XzJZu9PO5CISIMvgQ9+0Nf\n/iwDrLLNx0V0QeSGKEolKXJy9j83YUTZyea+fNT5i/r+BJV1WsUhIwST8P9UDOtk\n9cIArW8gE/K9gLE4xmIpQSTK5b1Eafue2+L+VaPoNqQTkP+cTX4BODgzmodHpBX/\niaRJjIRkrQKBgQCpMtH5j23pMOBPjitW2kTFeVXb7uWzEk1hfvYX8Bagaz/TC761\nWCyzO73KiCsCLy+8o1y39QvI/cptE7khmcGg8SfhkiGnBU9TcZLwJXf5g7C6ThSi\nEYr81sUMY6o7tJpAz6VjRhvWMytlqf6o9kvy+MHLo3coVOpe0NS7+WBfZQKBgHlf\nA6Mx8+7aYPaaApjchZaE8DnyKhMTDILlCb84Ew63C1R5Wj8KAvg5KmN6erZCedeX\nlKYSkkV6u9NM62Pxw3op533KT8bB3W+nQEz1mwA0Wb4/4STqldmGYUWocQ+Xk5wX\nyhND56xBBq2bE2VyN4lRhQfPO32/tHrpyS5MzT7ZAoGAHyGXsJqNW7PbHXMn8GMC\n5AGU3xppvIlM9n6dFNVtxh5B1xWOkCY5cdeplbNYn5ION1jrlcKXeuomG6i+Uyn+\nvFyFtjZjvPxvoLOaa1ZziJ7R5qXtlsAElgaCoU9tvFtP8RDSjIRSBgiXAnd/DyCv\n/Otk0Gb8R6styTJwiL3/FUM=\n-----END PRIVATE KEY-----\n"
      CLIENT_EMAIL: "ocr-access@ai-industry-projecr.iam.gserviceaccount.com"
      CLIENT_ID: "115662425364009750918"
      AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
      TOKEN_URI: "https://oauth2.googleapis.com/token"
      AUTH_PROVIDER_X509_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
      CLIENT_X509_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/ocr-access%40ai-industry-projecr.iam.gserviceaccount.com"
      UNIVERSE_DOMAIN: "googleapis.com"
    networks:
      - app-network

  drug-extractor-service:
    image: fhnass99/drug-extractor-service:latest
    container_name: drug-extractor-service
    ports:
      - "5003:5001"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "5000"
      OPENAI_API_KEY: "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"
    networks:
      - app-network

  ui:
    image: hsh24/ui
    container_name: ui
    ports:
      - "5004:5004"
    depends_on:
      - gateway
    networks:
      - app-network
  # detect-drug-interaction-service:
  #   image: fhnass99/detect-drug-interaction-service:latest
  #   container_name: detect-drug-interaction-service
  #   ports:
  #     - "5005:5005"
  #   # networks:
  #   #   - app-network

  # detect-drug-interaction-service:
  #   image: fhnass99/detect-drug-interaction-service:latest
  #   container_name: detect-drug-interaction-service
  #   ports:
  #     - "5005:5005"
  #   # networks:
  #   #   - app-network
  drug-interaction-service:
    image: hsh24/drug-interaction-service:latest
    container_name: drug-interaction-service
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "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"
      PINECONE_API_KEY: "pcsk_6gqt4x_J93voVvZDfnCFDxHLavKXCQhAdhVu7bcMALgAZHdebvRxqQiJkMZ8UWXgZgsDBv"
      INDEX_NAME: "pharma-bot-rag"
    networks:
      - app-network
  prometheus:
    image: prom/prometheus:latest
    container_name: pharmbot-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: pharmbot-grafana
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
