version: '3.8'
services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./data_pipeline/data/drugs_files/db:/data
  drug_extractor_service:

    build:
      context: ./drug_extractor_service
      dockerfile: Dockerfile
    container_name: drug_extractor_service
    ports:
      - "5000:5000"

  image_processing_service:
    build:
      context: ./medicine_detection_service
      dockerfile: Dockerfile
    container_name: medicine_detection_service
    ports:
      - "5001:5001"