---
apiVersion: v1
kind: Namespace
metadata:
  name: pharma-bot

---
# Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: hsh24/gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "5000"
            - name: DETECTION_URL
              value: "http://medicine-detection-service:5001/detect"
            - name: OCR_URL
              value: "http://ocr-service:5001/extracted_text"
            - name: EXTRACTOR_URL
              value: "http://drug-extractor-service:5000/extract"
            - name: INTERACTION_URL
              value: "http://drug-interaction-service:8000/rag"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: pharma-bot
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000

---
# OCR Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-service
  template:
    metadata:
      labels:
        app: ocr-service
    spec:
      containers:
        - name: ocr-service
          image: hsh24/ocr-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/key.json"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "5001"
            - name: TYPE
              value: "service_account"
            - name: PROJECT_ID
              value: "ai-industry-projecr"
            - name: PRIVATE_KEY_ID
              value: "a704038c00a082cb5da72be187de0aa660b21701"
            - name: PRIVATE_KEY
              value: |
                -----BEGIN PRIVATE KEY-----
                MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCimdMfTju07MAx
                mb5ktRLXgKa2bIz6j6L28LZKsyOp/f4/H9yyPiXbWXf16UggauHXJYS8Uc0Aaxxo
                ud40YFLdL2lcxZRBJR7yzv3MfW4LDRujI1zHR1JSxubARPUg+IBP/8dMoeVV15Hx
                RFHI6tVqSUQfsDg0SlBjYZSipdCZlLzN5r1vwnBbaQzZwwcyMzBsK2cmZrDrRE7D
                sBs/lgeJ2lWwzteS4ktlY8+8uiF3EeY2fLmy2hLed/PXGcaYig/VAwUgq8UXkgRE
                PvaNCjTuZoCsqNqQVxwj/Nwvkdsbm1OVbZd02JPceqDX0XC3laUtV0sWt0T4WTqT
                CB7E8WtTAgMBAAECggEAEA01bU1mJtnfA0Z/0tCZTT2TDPExsvkuXPMDBo7MAi0O
                ...
                /Otk0Gb8R6styTJwiL3/FUM=
                -----END PRIVATE KEY-----
            - name: CLIENT_EMAIL
              value: "ocr-access@ai-industry-projecr.iam.gserviceaccount.com"
            - name: CLIENT_ID
              value: "115662425364009750918"
            - name: AUTH_URI
              value: "https://accounts.google.com/o/oauth2/auth"
            - name: TOKEN_URI
              value: "https://oauth2.googleapis.com/token"
            - name: AUTH_PROVIDER_X509_CERT_URL
              value: "https://www.googleapis.com/oauth2/v1/certs"
            - name: CLIENT_X509_CERT_URL
              value: "https://www.googleapis.com/robot/v1/metadata/x509/ocr-access%40ai-industry-projecr.iam.gserviceaccount.com"
            - name: UNIVERSE_DOMAIN
              value: "googleapis.com"
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
  namespace: pharma-bot
spec:
  selector:
    app: ocr-service
  ports:
    - port: 5001
      targetPort: 5001

---
# Drug Extractor Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drug-extractor-service
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drug-extractor-service
  template:
    metadata:
      labels:
        app: drug-extractor-service
    spec:
      containers:
        - name: drug-extractor
          image: hsh24/drug-extractor-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "5000"
            - name: OPENAI_API_KEY
              value: "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"
---
apiVersion: v1
kind: Service
metadata:
  name: drug-extractor-service
  namespace: pharma-bot
spec:
  selector:
    app: drug-extractor-service
  ports:
    - port: 5000
      targetPort: 5000

---
# Drug Interaction Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drug-interaction-service
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drug-interaction-service
  template:
    metadata:
      labels:
        app: drug-interaction-service
    spec:
      containers:
        - name: interaction-service
          image: hsh24/drug-interaction-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              value: "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"
            - name: PINECONE_API_KEY
              value: "pcsk_6gqt4x_J93voVvZDfnCFDxHLavKXCQhAdhVu7bcMALgAZHdebvRxqQiJkMZ8UWXgZgsDBv"
            - name: INDEX_NAME
              value: "pharma-bot-rag"
---
apiVersion: v1
kind: Service
metadata:
  name: drug-interaction-service
  namespace: pharma-bot
spec:
  selector:
    app: drug-interaction-service
  ports:
    - port: 8000
      targetPort: 8000

---
# Medicine Detection Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicine-detection-service
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicine-detection-service
  template:
    metadata:
      labels:
        app: medicine-detection-service
    spec:
      containers:
        - name: detection-service
          image: hsh24/medicine-detection-model:latest
          ports:
            - containerPort: 5001
          env:
            - name: MODEL_PATH
              value: "src/model/yolo11.pt"
            - name: MODEL_FILE_ID
              value: "12k1Ni6QKxevlEeWp5Z7360HxEdT_7EQK"
---
apiVersion: v1
kind: Service
metadata:
  name: medicine-detection-service
  namespace: pharma-bot
spec:
  selector:
    app: medicine-detection-service
  ports:
    - port: 5001
      targetPort: 5001

---
# UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: hsh24/ui:latest
          ports:
            - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: pharma-bot
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 5004

---
# Prometheus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: pharma-bot
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

---
# Grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: pharma-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: pharma-bot
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
