{
 "title": "OCR Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ocr_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ocr_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/ms" } },
   "targets": [
    {
     "expr": "sum(rate(ocr_errors_total{error_type=\"5xx\"}[5m])) / sum(rate(ocr_requests_total[5m])) * 100",
     "legendFormat": "5xx Error Rate"
    },
    {
     "expr": "sum(rate(ocr_errors_total{error_type=\"4xx\"}[5m])) / sum(rate(ocr_requests_total[5m])) * 100",
     "legendFormat": "4xx Error Rate"
    }
   ]
  },
  {
   "title": "Text Length Cumalative Count (per 100 chars)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(ocr_text_length_total)/100", "legendFormat": "Text Length (100 chars)" }
   ]
  }
 ]
}